Interfaces.c does not get compiled on SL7 platform.
n SL7 Compiler errors out with ././Interfaces.c:554:47: error: lvalue required as unary '&' operand
        if(inet_ntop(arp_msg.arp_pa.sa_family, &(((struct sockaddr_in)addr_dummy).sin_addr),

On SLF6 it compiles well.

Also removed unused variable.

http://srm.fnal.gov/reviews/r/601/
http://www-ccf.fnal.gov/Bugzilla/show_bug.cgi?id=2067